[tool.poetry]
name = "ddns_digital_ocean"
version = "0.3.0"
description = "Python-based CLI tool for managing dynamic dns."
authors = ["Tyler Nivin <tyler@nivin.tech>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
do_ddns = 'ddns_digital_ocean.ddns:run'


[tool.poetry.dependencies]
python = "^3.9"
rich = "^13.6.0"
requests = "^2.31.0"

[tool.poetry.group.linters.dependencies]
ruff = "^0.6.2"

[tool.ruff]
# Uncomment to over-ride the line-length used by ruff.
# Allowing line-length 100 for now due to prior code.
line-length = 100

[tool.ruff.lint]
# Configure which ruff rules to enable.
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # Unused noqa comments
    "RUF100",
    # Flake8-bandit
    "S"
]
