[tool.poetry]
name = "ddns_digital_ocean"
version = "0.2.1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.scripts]
do_ddns = 'ddns_digital_ocean.ddns:run'


[tool.poetry.dependencies]
python = "^3.9"
rich = "^13.6.0"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
