[tool.poetry]
name = "ddns_digital_ocean"
version = "0.3.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
do_ddns = 'ddns_digital_ocean.ddns:run'


[tool.poetry.dependencies]
python = "^3.9"
rich = "^13.6.0"
requests = "^2.31.0"

[tool.poetry.group.linters.dependencies]
ruff = "^0.1.3"

[tool.ruff]
line-length = 100